### PR TITLE
Adding Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by renancouto**

### CODE REVIEW

**Comment by antoinejaussoin** [comment]
Thanks for this! Is there any way you could actually resubmit your PR and target the develop branch? I just changed my default branch to develop so it should be the default now (but I think you need to re-create a new PR... sorry for the inconvenience)

**Comment by antoinejaussoin** [comment]
Forget my last comment (just deleted it :)) I'm manually merging to develop!

Thanks for your translations, greatly appreciated !

**Comment by antoinejaussoin** [comment]
One comment: the sentence 'Gentilmente participando conosco agora:' is a bit long to fit on the side bar, any way we could shorten that?

**Comment by renancouto** [comment]
Sure, we could remove the "Gentilmente" word, which sounds a bit awkward in Portuguese anyways. Would that work?

**Comment by antoinejaussoin** [comment]
Done :)

-- 
Antoine Jaussoin
Sent with Airmail

On 3 April 2016 at 18:11:52, Renan Couto (notifications@github.com) wrote:

Sure, we could remove the "Gentilmente" word, which sounds a bit awkward in Portuguese anyways. Would that work?

**Comment by antoinejaussoin** [comment]
Hi @renancouto , I added a few extra strings in the pt-br.js file, I wondered if you could translate them? They are all marked with 'todo', on develop:
https://github.com/antoinejaussoin/retro-board/blob/develop/app/i18n/pt-br.js

Thanks!

**Pull request closed without merging**
