### PR TITLE
Add dutch translations

### PR DESCRIPTION
**Pull request by Sonaryr**

### CODE REVIEW

**Comment by antoinejaussoin** [comment]
Superb, thanks!

**Comment by antoinejaussoin** [comment]
It will be deployed on the next release (1 or 2 days from today), thanks again :)

**Comment by Sonaryr** [comment]
no problem

**Comment by antoinejaussoin** [comment]
Hi @Sonaryr , I added a few extra strings in the nl.js file, I wondered if you could translate them? They are all marked with 'todo', on develop:
https://github.com/antoinejaussoin/retro-board/blob/develop/app/i18n/nl.js

Thanks!

**Pull request merged**
